### ISSUE TITLE
Трейсбек сразу при загрузке страницы Годвилля

### ISSUE THREAD

**Issue by msva** [zeird/godville-ui-plus#5]
Привет! Сразу после установки дополнения и последующей перезагрузки страницы годвилля вываливается нижеследующий трейсбек. И так происходит при каждой перезагрузке страницы. При этом, вроде как, всё остальное работает...
```
Браузер: Firefox 35.0.
Версия: 0.25.111.21.
Текст ошибки: : .
Трассировка стека: ui_utils.getXHR@247:1
ui_trycatcher.replace_with/<@2445:10
ui_data._getLEMRestrictions@88:2
ui_trycatcher.replace_with/<@2445:10
ui_data.init@25:1
ui_trycatcher.replace_with/<@2445:10
ui_starter._init@2487:1
ui_trycatcher.replace_with/<@2445:10
ui_starter.start@2507:2
ui_trycatcher.replace_with/<@2445:10
```

**Comment by zeird** [comment]
Для корректной работы дополнение должно подтянуть инфу из внешнего места. И так как то внешнее место работает только на `http`, при игре на `https` `Firefox` блочит эту загрузку и выдается эта ошибка. Для действительно корректной работы нужно разрешить смешанный контент.
![](http://i.imgur.com/2c4q5SM.png)

**Comment by msva** [comment]
1) нет, годвилль открыт не по HTTPS.
2) в любом случае, разрешать нбезопасные источники — плохая практика 😓

**Comment by zeird** [comment]
1) Еще загрузка может блочиться чем-то вроде `NoScript`. Если так, то разреши `godalert.info`.
2) Я в курсе. Однако альтернатив у меня нет. Сервер **ЛЕМа** крутится только на `http`.
