### ISSUE TITLE
Сбрасываются настройки карты в подземелье

### ISSUE THREAD

**Issue by lexfrei** [zeird/godville-ui-plus#9]
Собственно, сабж.
Каждый раз при походе в подземелье приходится возвращать галочку про карту на место.

**Comment by zeird** [comment]
Допустим, речь идет о флажке "Поменять местами пульт и карту". Сбрасываются все настройки или только эта?

**Comment by lexfrei** [comment]
По крайней мере она.
Поставил ещё галочек, посмотрим как поведёт себя.
Проблема замечена в последней стабильной версии chrome на win8.1, os x 10.7 и fedora 21

**Comment by zeird** [comment]
Может, в личку напишешь? Это будет быстрее и проще.

**Comment by lexfrei** [comment]
Без проблем. Просто предпочитаю отмечать баги на гитхабе.

**Comment by zeird** [comment]
Проблема оказалась в том, что у пользователя по неизвестным причинам удаляются кукисы, а вместе с ними и очищается localStorage, в котором в т.ч. хранятся настройки аддона.
